### ISSUE TITLE
Probable errors in goa_uniprot_all_noiea.gaf file

### ISSUE THREAD

**Issue by rzelayafavila** [geneontology/helpdesk#72] opened 2017-11-13 16:55 UTC
This file contains the following text on line 1439605, which is making my script fail:
`gzip: goa_uniprot_all.gaf.gz: unexpected end of file`.

Also, the very last line of the file looks like it is unexpectedly truncated:
`UniProtKB	V9VXB2	infB		GO:000`

This is the version information at the top of the file:
```
!Generated: 2017-10-23 13:41 
!GO-version: http://purl.obolibrary.org/obo/go/releases/2017-10-21/extensions/go-plus.owl
```
Thanks!
Rene

**Comment by kltm** [comment] 2017-11-13 18:52
@rzelayafavila Could you give us the URL that you used for this download and/or where you found it?

**Comment by rzelayafavila** [comment] 2017-11-13 18:56
Yes, of course, it is in the gene annotation files in ftp downloads:
`ftp://ftp.geneontology.org/go/gene-associations/goa_uniprot_all_noiea.gaf.gz`

**Comment by kltm** [comment] 2017-11-14 02:21
@rzelayafavila Thank you for your help. We've confirmed the issue on this end (if not the origin yet) and have tried to revert. This should hopefully be percolating out some time this evening. We'll be checking on this again tomorrow.

**Comment by cmungall** [comment] 2017-11-14 06:09
The problem is now fixed, thanks!

**Closed by cmungall** 2017-11-14 06:09 UTC
Labels: accepted, Downloads, Other, Software

**Comment by rzelayafavila** [comment] 2017-11-14 15:58
Great, thank you!
