### ISSUE TITLE
ECO code in gpa files not seen in https://github.com/evidenceontology

### ISSUE THREAD

**Issue by dvklopfenstein** [geneontology/helpdesk#372] opened 2021-12-21 19:36 UTC
## ECO code in gpa files not seen in https://github.com/evidenceontology

These ECO codes are seen in gpa files from ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/, but not seen in https://github.com/evidenceontology/evidenceontology/blob/master/gaf-eco-mapping-derived.txt:

```
**ERROR:     14,035 INSTANCES OF ECO:0005547 IN GPAs
**ERROR:      3,390 INSTANCES OF ECO:0005544 IN GPAs
**ERROR:        712 INSTANCES OF ECO:0005546 IN GPAs
**ERROR:        470 INSTANCES OF ECO:0005610 IN GPAs
**ERROR:        152 INSTANCES OF ECO:0005543 IN GPAs
```

Is there another main ECO file that I should be using rather than the one from [evidenceontology](https://github.com/evidenceontology/evidenceontology/blob/master/gaf-eco-mapping-derived.txt)?

## Expected behavior
Checkers for gpa annotation files should ensure the ECO codes in gpa files are also seen in the main evidenceontology file (if that is the correct main file) so researchers using the gpa files do not see errors or missing information.

## To Reproduce
Look in the ECO definition file:
https://github.com/evidenceontology/evidenceontology/blob/master/gaf-eco-mapping-derived.txt

And see that these gpas contain ECO codes that do not exist in the ECO definition file:
```
  ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/ARABIDOPSIS/goa_arabidopsis.gpa.gz
  ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/CHICKEN/goa_chicken.gpa.gz
  ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/COW/goa_cow.gpa.gz
  ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/FLY/goa_fly.gpa.gz
  ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/HUMAN/goa_human.gpa.gz
  ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/MOUSE/goa_mouse.gpa.gz
  ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/PIG/goa_pig.gpa.gz
  ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/RAT/goa_rat.gpa.gz
  ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/WORM/goa_worm.gpa.gz
  ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/YEAST/goa_yeast.gpa.gz
  ftp://ftp.ebi.ac.uk/pub/databases/GO/goa/ZEBRAFISH/goa_zebrafish.gpa.gz
```

## Additional context
All files downloaded Dec 21, 2021

**Comment by kltm** [comment] 2021-12-21 22:09
@dvklopfenstein Just to clarify the issue here a little, the gaf-eco-mapping-derived.txt file provides mapping information between ECO and GAF evidence codes, as part of the GAF format (http://geneontology.org/docs/go-annotation-file-gaf-format-2.1/ and http://geneontology.org/docs/guide-go-evidence-codes/).
The range of evidence in the GPAD 1.1 format (http://geneontology.org/docs/gene-product-association-data-gpad-format/) is essentially anything in ECO (https://evidenceontology.org/download/ mostly backed by https://github.com/evidenceontology/evidenceontology). If your are looking for a smaller file to work with, you might want to take a look at 
https://github.com/evidenceontology/evidenceontology/blob/master/eco-basic.obo .

If it's the case that the ECO identifiers should be found in the GAF mapping, since the mapping file is derived from the evidence ontology itself, it might be best to open a ticket in their tracker and have it added for their next release.

Also tagging @cmungall and @vanaukenk .

**Comment by vanaukenk** [comment] 2021-12-21 22:18
@kltm @dvklopfenstein 

There are two tickets related to this issue in the ECO tracker:
https://github.com/evidenceontology/evidenceontology/issues/262
https://github.com/evidenceontology/evidenceontology/issues/264

My understanding is that these codes will be mapped to IC in the derived file; the tickets have a lot more discussion and details, if needed.

**Comment by kltm** [comment] 2021-12-21 22:22
Thank you @vanaukenk . I'll close this issue as a duplicate of those. @dvklopfenstein You may wish to follow those issues and participate in the conversation there.

**Closed by kltm** 2021-12-21 22:22 UTC
Labels: accepted, Other
