### ISSUE TITLE
issue in GO obo file, possibly related to GO:0015307

### ISSUE THREAD

**Issue by sabrinatoro** [geneontology/helpdesk#207] opened 2019-04-23 19:11 UTC
The ZFIN Gene Ontology load has been falling since April 10th due to some error in the OBO file. 
It looks like the issue is with the term: drug:proton antiporter activity (GO:0015307). 
This term appears to be obsoleted in the current obo file, but is also used as a “consider” term for another term (GO:0015525, also obsolete)

**Comment by cmungall** [comment] 2019-04-23 19:16
Thanks. @ukemi do you want this transferred to the go-ontology repo or just fix from here?

Let's discuss the validation pipeline when @dougli1sqrd is back next week on the ontology call, I thought the pipeline should block this.

**Comment by ukemi** [comment] 2019-04-23 22:58
I've opened a PR to fix this here. It's a simple fix, but I also thought we had a check for validity of consider terms. Maybe it was just implemented for replaced_by.

**Comment by ukemi** [comment] 2019-04-23 22:59
go-ontology/pull/17180

**Closed** 2019-04-24 01:27 UTC
Labels: Ontology, accepted

**Comment by sierra-moxon** [comment] 2019-04-24 15:40
Hi - can you give us a timeline of when we should see this change in the file itself?  We currently retrieve the obo file from this URL: http://purl.obolibrary.org/obo/go/snapshot/go.obo (do we need to get it from an alternate location?)  Thanks in advance, Sierra :)

**Comment by ukemi** [comment] 2019-04-24 17:03
It should be available in the next snapshot release. Looks like the latest was on the 18th. @kltm ?

**Comment by kltm** [comment] 2019-04-24 17:41
The last successful `snapshot` should have been the 23rd. If something has not propagated properly, we should look into that. The system had a race last night and failed; I expect it to restart at midnight tonight and finalize around 2-3pm tomorrow.

**Comment by ukemi** [comment] 2019-04-24 17:57
The file header for go.obo lists the 18th. I suspect there is an issue somewhere. Does that need a separate ticket.

**Comment by kltm** [comment] 2019-04-24 18:41
@ukemi I can confirm that a new version was uploaded to `snapshot` on the 23rd, it propagated out, and that is has `data-version: releases/2019-04-18`. That seems wrong and probably deserves a ticket.
Now then, taking a peak at what is currently in the (failed) pipeline run, I can see that go.obo had data-`version: releases/2019-04-24`, so the error may have cleared itself.

**Comment by ukemi** [comment] 2019-04-24 19:19
OK. The file I'm downloading from snapshot still has the stanza below, which is out of date. I just reconfirmed that my changes are in the editors' version of the ontology. @kltm, do you think snapshot just hasn't caught up? I made the change last night.

[Term]
id: GO:0015525
name: obsolete carbonyl cyanide m-chlorophenylhydrazone/nalidixic acid/organomercurials:hydrogen antiporter activity
namespace: molecular_function
def: "OBSOLETE (was not defined before being made obsolete)." [GOC:ai]
comment: This term was made obsolete because it represents a multifunctional gene product.
synonym: "carbonyl cyanide m-chlorophenylhydrazone/nalidixic acid/organomercurials:hydrogen antiporter activity" EXACT []
synonym: "carbonyl cyanide m-chlorophenylhydrazone/nalidixic acid/organomercurials:proton antiporter activity" EXACT []
is_obsolete: true
consider: GO:0015307-------This is deleted in the editors' version
consider: GO:0015547
consider: GO:0015548
consider: GO:0015549

**Comment by kltm** [comment] 2019-04-24 21:26
Cross-reference https://github.com/geneontology/pipeline/issues/90

**Comment by kltm** [comment] 2019-04-24 21:27
@ukemi The most recent thing we have is here:
http://skyhook.berkeleybop.org/snapshot/ontology/go.obo
The `consider` seems to be deleted.

**Comment by ukemi** [comment] 2019-04-25 14:22
Thanks @kltm. This still odesn't seem to be in the snapshot release though. I would suggest that @sierra-moxon continues to try to get the file from:
http://purl.obolibrary.org/obo/go/snapshot/go.obo

If you disagree, please comment.

**Comment by kltm** [comment] 2019-04-25 21:38
@ukemi Release does not finish until about 3pm PDT.

**Comment by kltm** [comment] 2019-04-25 21:43
Checking all the usual places, it looks to now be propagated.

**Comment by kltm** [comment] 2019-04-25 21:44
Noting date is aligned as well.

**Comment by sabrinatoro** [comment] 2019-04-25 21:56
We had a successful load! 
Thanks for your help!

**Comment by ukemi** [comment] 2019-04-26 12:12
Thanks @kltm!!
